name: trailbuddy
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

#----------------PACKAGES----------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.3.0
  url_launcher: ^6.3.0
  flutter_native_splash: ^2.4.1
  smooth_page_indicator: ^1.2.0

  # Icons
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

#---------------- ./ PACKAGES END ----------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

dependency_overrides:
  collection: ^1.19.0
  meta: ^1.15.0
  leak_tracker: ^10.0.5
  leak_tracker_flutter_testing: ^3.0.5
  material_color_utilities: ^0.12.0
  test_api: ^0.7.2
  # Align vm_service with flutter_test requirement
  vm_service: 14.2.1

flutter:
  uses-material-design: true

  #------------------ LOCAL ASSETS -------------#
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/on_boarding_images/
    - assets/images/others/

  #------------------ LOCAL FONTS --------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
